web:
  build: .
  dockerfile: Dockerfile
  ports:
    - "80:80"
  links:
    - mysql
  volumes:
    - "./build:/var/www/html"

mysql:
  image: mariadb
  ports:
    - "33306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: mysql
